/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clickandobey.dockerized.webservice;

import org.junit.jupiter.api.Test;

public class PlaceHolderTest {
    @Test public void testPlaceholder() {
    }
}
